# Generated by Django 5.0.6 on 2024-05-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CCTV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_code', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('managing_agency', models.CharField(max_length=100)),
                ('address_road', models.CharField(max_length=200)),
                ('address_jibun', models.CharField(max_length=200)),
                ('purpose', models.CharField(max_length=100)),
                ('camera_count', models.IntegerField()),
                ('resolution', models.CharField(max_length=100)),
                ('direction_info', models.CharField(max_length=200)),
                ('retention_period', models.IntegerField()),
                ('installation_date', models.DateField()),
                ('managing_agency_phone', models.CharField(max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('data_standard_date', models.DateField()),
            ],
        ),
    ]
