# Generated by Django 5.0.6 on 2024-05-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0002_alter_cctv_address_jibun_alter_cctv_direction_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvenienceStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('sr_nm', models.CharField(max_length=100)),
                ('adres', models.CharField(max_length=100)),
                ('tel_no', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('detail_adr', models.CharField(max_length=100)),
                ('sigungu', models.CharField(max_length=100)),
                ('sido', models.CharField(max_length=100)),
                ('umd', models.CharField(max_length=100)),
            ],
        ),
    ]
